const fs=require('node:fs'),path=require('node:path');const root=path.join(__dirname,'..'),dist=path.join(root,'dist');
const files=['index.html','control-room.css','reference-theme.css','operations-ui.js','traffic-lab.js','traffic-ui.js','vendor/qrcode.js','vendor/jsQR.js','vendor/JSQR-LICENSE.txt','pages.js','styles.css','app.js','model.js','map-data.js','planning-model.js','planning-ui.js','readiness-model.js','readiness-ui.js','vendor/leaflet.js','vendor/leaflet.css','vendor/LEAFLET-LICENSE.txt'];
const assets=Object.fromEntries(files.map(f=>['/'+f,fs.readFileSync(path.join(dist,f),'utf8')]));
const model=['map-data.js','model.js','readiness-model.js','planning-model.js'].map(f=>assets['/'+f]).join('\n');
const handler=fs.readFileSync(path.join(root,'server/handler.mjs'),'utf8').replace('export async function','async function');
const operations=fs.readFileSync(path.join(root,'server/operations.mjs'),'utf8').replace('export async function','async function');
const code=`${operations}\n${model}\n${handler}\nconst assets=${JSON.stringify(assets)};\nexport default {async fetch(request,env){const api=(await operationsAPI(request,env)) || (await scenarioAPI(request,env,globalThis.PlanningModel.validate));if(api)return api;const url=new URL(request.url);const name=['/','/studio','/comparison','/timeline','/report','/studio/','/comparison/','/timeline/','/report/','/visitor','/operator','/traffic','/visitor/','/operator/','/traffic/'].includes(url.pathname)?'/index.html':url.pathname;if(!['GET','HEAD'].includes(request.method))return new Response('Method not allowed',{status:405});if(!(name in assets))return new Response('Not found',{status:404});const type=name.endsWith('.js')?'application/javascript':name.endsWith('.css')?'text/css':name.endsWith('.html')?'text/html':'text/plain';return new Response(request.method==='HEAD'?null:assets[name],{headers:{'Content-Type':type+'; charset=utf-8','X-Content-Type-Options':'nosniff','Cache-Control':'no-cache'}})}};\n`;
fs.mkdirSync(path.join(dist,'server'),{recursive:true});fs.writeFileSync(path.join(dist,'server/index.js'),code);console.log('Worker built with embedded frontend assets and cloud scenario storage.');


const metadata=path.join(dist,'.openai');fs.mkdirSync(metadata,{recursive:true});fs.copyFileSync(path.join(root,'.openai/hosting.json'),path.join(metadata,'hosting.json'));fs.cpSync(path.join(root,'drizzle'),path.join(metadata,'drizzle'),{recursive:true});
